In [49]:
import numpy as np

import nltk

import spacy
from spacy_langdetect import LanguageDetector

In [41]:
import time, sys
from IPython.display import clear_output

def update_progress(progress):
    bar_length = 20
    if isinstance(progress, int):
        progress = float(progress)
    if not isinstance(progress, float):
        progress = 0
    if progress < 0:
        progress = 0
    if progress >= 1:
        progress = 1

    block = int(round(bar_length * progress))

    clear_output(wait = True)
    text = "Progress: [{0}] {1:.1f}%".format( "#" * block + "-" * (bar_length - block), progress * 100)
    print(text)


In [ ]:
path = 'data/cleaned.npy'
arr = np.load(path, allow_pickle = True)

In [7]:
arr.shape

(40627, 4)

In [20]:
words = arr[:,3]

In [63]:
nlp = spacy.load("en")
nlp.add_pipe(LanguageDetector(), name="language_detector", last=True)

lang = []
for idx, w in enumerate(words):
    if len(w)<4:
        lang.append(-1)
    else:
        doc = nlp(w)
        lang.append(doc._.language['language'])
    progress_bar = idx
    update_progress((idx+1) / len(words))
    




Progress: [####################] 100.0%


In [65]:
len(words)

40627

In [72]:
l =np.array(lang)
l.shape
l =l.reshape(-1,1)

In [77]:
arr2 = np.concatenate((arr,l), axis = 1 )

In [78]:
arr2.shape

(40627, 5)

In [81]:
arr2[3]

array([5, '1927303-mary', ('Paperback 9781435756342',),
       'Live love laugh a Lot is a special book.Interesting characters make you laugh- you must take a look.Voicing their opinions in humorous forms moving line by line.Entertaining to such an extent- you must take your time.Love the way Jacquelyn speaks through Sly Fox.Over and over you have to laugh as he comes out of his box.Very sly he tries to be from behind his cloth.Excitement on each page you must laugh a lot.Laughter rings out as Ingrid does her stuff.A woman who could finally say, “Enough is Enough”.Use me Lord Jacquelyn says on page fifty-eight.God’s blessings comes in many ways Jacquelyn points out to us.Honesty and humor you will find within these pages so much.A great read and must for every home.Live Love Laugh a lotOh how humorousThis book is written by Jacquelyn Sturge ',
       'en'], dtype=object)

In [82]:
np.save("data/clean_and_lang", arr2) ## might need to do a mongo thing


(40627, 5)

array(['de', 'en', 'it', ..., 'en', 'en', 'en'], dtype=object)

In [89]:
u_languages, lang_counts  = np.unique(lang, return_counts = True)

#### get breakdown of the languages in the set

In [159]:
u_languages, lang_counts  = np.unique(lang, return_counts = True)
breakdown = [i for i in zip(u_languages, lang_counts)]
breakdown.sort(key = lambda t: t[1], reverse = True)

add = 0
for items in breakdown:
    add += items[1]

# breakdown

In [211]:
lang = arr2[:,-1]
lang.reshape(-1,1)
mask = np.array([True if i == 'en' else False for i in lang])
english = arr2[mask]
english.shape
#  english[0]

(39644, 5)

In [157]:
percent_english = english.shape[0]/arr.shape[0]
percent_english

0.9758042680975706

### Sort the reviews into star buckets

In [161]:
english[2]

array([5, '2009689-christina-jussaume', ('Paperback 9781435756342',),
       "Live, laugh, Love A LotJay’s limericks are entertainingYour smile will stay on face remainingPastor series is greatYou will appreciateReading muse you’ll not be complainingShe writes with humor on many thingsLoud hysterical laughter she bringsYour spirit she’ll raise highYou’ll read and often sigh She wrote with humor of wedding rings Humor brings out positive effectShe does write on many a subjectShe will enlighten youWords from her soul are trueShe will tell you smile as not perfectHer book I would highly recommendI think I’ll read it over againIt has beat that’s uniqueGet copy and take peekIt can be enjoyed like a best friend By Christina R Jussaume copyright 2009*This is a series of limericks for Jacqueline Sturge's first book__________________",
       'en'], dtype=object)

In [204]:
english[:0,0:-1]
english.shape

(39644, 5)

In [216]:
ratings = english[:, 0]
ratings.shape

(39644,)

In [221]:
rnot_rated_mask = r2_mask = np.array([True if i == -1 else False for i in ratings])
r1_mask = np.array([True if i == 1 else False for i in ratings])
r2_mask = np.array([True if i == 2 else False for i in ratings])
r3_mask = np.array([True if i == 3 else False for i in ratings])
r4_mask = np.array([True if i == 4 else False for i in ratings])
r5_mask = np.array([True if i == 5 else False for i in ratings])

In [220]:
r1_mask.reshape(-1,1

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [222]:
rated_1 = english[r1_mask.reshape(-1,1)]


IndexError: boolean index did not match indexed array along dimension 1; dimension is 5 but corresponding boolean dimension is 1

In [191]:
r1_mask.reshape(-1,1)

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])